//{{NO_DEPENDENCIES}}
// Microsoft Visual C++���� ������ ���� �����Դϴ�.
// CustomerClient.rc���� ���ǰ� �ֽ��ϴ�.
//
#define IDD_ABOUTBOX                    100
#define IDD_CUSTOMERCLIENT_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN_DLG                   129
#define IDD_MAINHOME_DLG                131
#define IDD_STORELIST_DLG               133
#define IDD_DIALOG1                     135
#define IDD_MENUDETAIL_DLG              135
#define IDD_CART_DLG                    137
#define IDD_PAYMENT_DLG                 139
#define IDD_ORDERHISTORY_DLG            141
#define IDD_CHAT_DLG                    143
#define IDD_STOREDETAIL_DLG             145
#define IDD_DELIVERY_OK_DLG             147
#define IDD_REVIEW_LIST_DLG             149
#define IDD_REVIEW_WRITE_DLG            151
#define IDD_DIALOG2                     153
#define IDD_DIALOG_OPTION_CHANGE        153
#define IDD_ORDERLIST_DLG               155
#define ORDERLISTDLG                    200
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1002
#define IDC_LIST_STOR                   1004
#define IDC_STATIC_RECT                 1005
#define IDC_STATIC_TOP_BG               1006
#define IDC_STATIC_MENU_BAR             1007
#define IDC_STATIC_PICKUP               1008
#define IDC_BTN_PAGE1                   1009
#define IDC_BTN_PAGE2                   1010
#define IDC_BTN_PAGE3                   1011
#define IDC_BTN_NEXT                    1012
#define IDC_BTN_MYPAGE                  1013
#define IDC_STATIC_BG                   1014
#define IDC_BTN_CART                    1200
#define IDC_STATIC_STORE_IMG            1201
#define IDC_BTN_STORE_INFO              1202
#define IDC_STATIC_SUB_MENU_BAR         1203
#define IDC_LIST_MENU_ITEMS             1204
#define IDC_BTN_PREV_PAGE               1205
#define IDC_BTN_NEXT_PAGE               1206
#define IDC_STATIC_PAGE_NUM             1207
#define IDC_STATIC_MENU_NAME_D          1251
#define IDC_EDIT_MENU_DESC_D            1252
#define IDC_STATIC_OPTION_GROUP_D       1253
#define IDC_LIST_OPTIONS_D              1254
#define IDC_STATIC_BOTTOM_GROUP_D       1255
#define IDC_STATIC_BASE_PRICE_D         1256
#define IDC_STATIC_OPTION_PRICE_D       1257
#define IDC_BTN_ADD_CART_D              1258
#define IDC_BTN_REVIEW_BACK             1300
#define IDC_STATIC_REVIEW_TITLE         1301
#define IDC_COMBO_STAR_RATING           1302
#define IDC_EDIT_REVIEW_CONTENT         1303
#define IDC_BTN_REVIEW_SUBMIT           1304
#define IDC_BTN_BACK                    1400
#define IDC_RADIO_DELIVERY              1401
#define IDC_RADIO_PICKUP                1402
#define IDC_BTN_EDIT_OPTION             1403
#define IDC_BTN_EDIT_QUANTITY           1404
#define IDC_COMBO_PAYMENT               1405
#define IDC_STATIC_MENU_NAME            1406
#define IDC_STATIC_OPTION_TEXT          1407
#define IDC_STATIC_ORDER_PRICE          1408
#define IDC_STATIC_DELIVERY_FEE         1409
#define IDC_STATIC_TOTAL_PRICE          1410
#define IDC_LIST_CART                   1411
#define IDD_EDIT_OPTION_DLG             1500
#define IDC_STATIC_SELECTED_MENU        1501
#define IDC_LIST_OPTIONS                1502
#define IDC_BTN_COUNT_MINUS             1503
#define IDC_BTN_COUNT_PLUS              1504
#define IDC_EDIT_COUNT                  1505
#define IDC_STATIC_TOTAL_PRICE_POPUP    1506
#define IDC_EDIT_STORE_NAME             1601
#define IDC_EDIT_STORE_ADDR             1602
#define IDC_EDIT_STORE_TIME             1603
#define IDC_EDIT_STORE_OFF              1604
#define IDC_EDIT_STORE_TEL              1605
#define IDC_STATIC_STORE_NAME           1700
#define IDC_STATIC_ORDER_LIST           1701
#define IDC_STATIC_PRICE                1702
#define IDC_STATIC_TIME                 1703
#define IDC_BTN_WRITE_REVIEW            1704
#define IDC_BTN_CHAT_BACK               1750
#define IDC_STATIC_CHAT_TITLE           1751
#define IDC_LIST_CHAT_MSGS              1752
#define IDC_EDIT_CHAT_INPUT             1753
#define IDC_BTN_CHAT_SEND               1754
#define IDC_STATIC_ORDER_STATUS         1800
#define IDC_STATIC_ORDER_NUM            1801
#define IDC_STATIC_SHOP_NAME            1802
#define IDC_STATIC_ESTIMATED_TIME       1803
#define IDC_LIST_ORDER_ITEMS            1804
#define IDC_STATIC_FINAL_TOTAL          1805
#define IDC_BTN_CHAT                    1806
#define IDC_EDIT_LOGIN_ID               1900
#define IDC_EDIT_LOGIN_PW               1901
#define IDC_BTN_GOTO_SIGNUP             1902
#define IDC_STATIC_CONN_STATUS          1903
#define IDC_BTN_CONNECT                 1904
#define IDC_EDIT_SERVER_IP              1905
#define IDC_EDIT_SERVER_PORT            1906
#define IDC_STATIC_LOGIN_ERR            1907
#define IDC_EDIT_CARD_NAME              1910
#define IDC_EDIT_CARD_NUMBER            1911
#define IDC_EDIT_EXPIRY                 1912
#define IDC_EDIT_CVV                    1913
#define IDC_EDIT_PASSWORD               1914
#define IDC_LIST_CARDS                  1915
#define IDC_BTN_SET_DEFAULT             1916
#define IDC_BTN_DELETE_CARD             1917
#define IDD_SIGNUP_DLG                  1950
#define IDC_EDIT_SIGNUP_ID              1951
#define IDC_EDIT_SIGNUP_PW              1952
#define IDC_EDIT_SIGNUP_PW2             1953
#define IDC_EDIT_SIGNUP_NAME            1954
#define IDC_EDIT_SIGNUP_PHONE           1955
#define IDC_EDIT_SIGNUP_ADDR            1956
#define IDC_COMBO_SIGNUP_ROLE           1957
#define IDC_STATIC_SIGNUP_ERR           1958
#define IDC_BTN_MY_MYPAGE               1960
#define IDC_BTN_MY_PAYMENT              1961
#define IDC_BTN_MY_DELIVERY             1962
#define IDC_BTN_MY_ORDERHISTORY         1963
#define IDC_EDIT_DELIVERY_REQUEST       1970
#define IDC_STATIC_REQUEST_LABEL        1971
#define IDC_LIST_REVIEWS                1980
#define IDC_STATIC_REVIEW_STORE         1981
#define IDC_STATIC_AVG_RATING           1982
#define IDC_BTN_WRITE_MY_REVIEW         1983
#define IDC_BTN_COUNT_MINUS_D           2010
#define IDC_BTN_COUNT_PLUS_D            2011
#define IDC_EDIT_COUNT_D                2012
#define IDC_STATIC_TOTAL_D              2013
#define IDC_EDIT_DELIVERY_ADDR          2020
#define IDC_STATIC_ADDR_LABEL           2021
#define IDC_EDIT_USE_POINT              2022
#define IDC_STATIC_MY_POINT             2023
#define IDC_EDIT_COUPON_ID              2024
#define IDC_LIST_ORDER_HISTORY          2100
#define IDC_STATIC_OL_ORDER_NUM         2101
#define IDC_STATIC_OL_STORE_NAME        2102
#define IDC_STATIC_OL_DATETIME          2103
#define IDC_STATIC_OL_TOTAL             2104
#define IDC_STATIC_OL_STATUS            2105
#define IDC_LIST_OL_ITEMS               2106
#define IDC_STATIC_OL_EMPTY             2107
#define IDC_BTN_OL_WRITE_REVIEW         2108
#define IDC_STATIC_OL_METHOD            2109

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
